commonPath=/rest/api/1.0/projects
getCommitsInRange=/%s/repos/%s/commits?&since=%s&until=%s&start=%d
getLastXCommits=/%s/repos/%s/commits?limit=%d
getTags=/rest/api/latest/projects/%s/repos/%s/tags
getManifestFileContent=/projects/%s/repos/%/raw/%s/manifest/hawaii.yaml?at=
tagRefsQueryParam=refs/tags/%s
getCommitByHash=/%s/repos/%s/commits/%s